# Form implementation generated from reading ui file 'facturation_ci/ui/avoir_list_page.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AvoirListPage(object):
    def setupUi(self, AvoirListPage):
        AvoirListPage.setObjectName("AvoirListPage")
        AvoirListPage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(AvoirListPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.certify_button = QtWidgets.QPushButton(parent=AvoirListPage)
        self.certify_button.setObjectName("certify_button")
        self.horizontalLayout.addWidget(self.certify_button)
        self.print_button = QtWidgets.QPushButton(parent=AvoirListPage)
        self.print_button.setObjectName("print_button")
        self.horizontalLayout.addWidget(self.print_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_view = QtWidgets.QTableView(parent=AvoirListPage)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(AvoirListPage)
        QtCore.QMetaObject.connectSlotsByName(AvoirListPage)

    def retranslateUi(self, AvoirListPage):
        _translate = QtCore.QCoreApplication.translate
        AvoirListPage.setWindowTitle(_translate("AvoirListPage", "Gestion des Avoirs"))
        self.certify_button.setText(_translate("AvoirListPage", "Certifier (FNE)"))
        self.print_button.setText(_translate("AvoirListPage", "Imprimer"))
