# Form implementation generated from reading ui file 'ui/bl_viewer_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BLViewerDialog(object):
    def setupUi(self, BLViewerDialog):
        BLViewerDialog.setObjectName("BLViewerDialog")
        BLViewerDialog.resize(700, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(BLViewerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.details_groupbox = QtWidgets.QGroupBox(parent=BLViewerDialog)
        self.details_groupbox.setObjectName("details_groupbox")
        self.formLayout = QtWidgets.QFormLayout(self.details_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.label_code_bl = QtWidgets.QLabel(parent=self.details_groupbox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_code_bl.setFont(font)
        self.label_code_bl.setObjectName("label_code_bl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_code_bl)
        self.value_code_bl = QtWidgets.QLabel(parent=self.details_groupbox)
        self.value_code_bl.setObjectName("value_code_bl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.value_code_bl)
        self.label_date = QtWidgets.QLabel(parent=self.details_groupbox)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_date)
        self.value_date = QtWidgets.QLabel(parent=self.details_groupbox)
        self.value_date.setObjectName("value_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.value_date)
        self.label_facture = QtWidgets.QLabel(parent=self.details_groupbox)
        self.label_facture.setObjectName("label_facture")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_facture)
        self.value_facture = QtWidgets.QLabel(parent=self.details_groupbox)
        self.value_facture.setObjectName("value_facture")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.value_facture)
        self.verticalLayout.addWidget(self.details_groupbox)
        self.client_groupbox = QtWidgets.QGroupBox(parent=BLViewerDialog)
        self.client_groupbox.setObjectName("client_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.client_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_client_name = QtWidgets.QLabel(parent=self.client_groupbox)
        self.label_client_name.setObjectName("label_client_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_client_name)
        self.value_client_name = QtWidgets.QLabel(parent=self.client_groupbox)
        self.value_client_name.setObjectName("value_client_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.value_client_name)
        self.label_client_address = QtWidgets.QLabel(parent=self.client_groupbox)
        self.label_client_address.setObjectName("label_client_address")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_client_address)
        self.value_client_address = QtWidgets.QLabel(parent=self.client_groupbox)
        self.value_client_address.setWordWrap(True)
        self.value_client_address.setObjectName("value_client_address")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.value_client_address)
        self.verticalLayout.addWidget(self.client_groupbox)
        self.items_groupbox = QtWidgets.QGroupBox(parent=BLViewerDialog)
        self.items_groupbox.setObjectName("items_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.items_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.items_table_view = QtWidgets.QTableView(parent=self.items_groupbox)
        self.items_table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.items_table_view.setObjectName("items_table_view")
        self.verticalLayout_2.addWidget(self.items_table_view)
        self.verticalLayout.addWidget(self.items_groupbox)
        self.button_box = QtWidgets.QDialogButtonBox(parent=BLViewerDialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(BLViewerDialog)
        QtCore.QMetaObject.connectSlotsByName(BLViewerDialog)

    def retranslateUi(self, BLViewerDialog):
        _translate = QtCore.QCoreApplication.translate
        BLViewerDialog.setWindowTitle(_translate("BLViewerDialog", "Visualisation du Bordereau de Livraison"))
        self.details_groupbox.setTitle(_translate("BLViewerDialog", "Détails du Document"))
        self.label_code_bl.setText(_translate("BLViewerDialog", "Code BL :"))
        self.value_code_bl.setText(_translate("BLViewerDialog", "BL-XXXXXXXXX"))
        self.label_date.setText(_translate("BLViewerDialog", "Date de création :"))
        self.value_date.setText(_translate("BLViewerDialog", "YYYY-MM-DD"))
        self.label_facture.setText(_translate("BLViewerDialog", "Facture associée :"))
        self.value_facture.setText(_translate("BLViewerDialog", "F-XXXXXXXXX"))
        self.client_groupbox.setTitle(_translate("BLViewerDialog", "Informations Client"))
        self.label_client_name.setText(_translate("BLViewerDialog", "Nom :"))
        self.value_client_name.setText(_translate("BLViewerDialog", "Nom du client"))
        self.label_client_address.setText(_translate("BLViewerDialog", "Adresse :"))
        self.value_client_address.setText(_translate("BLViewerDialog", "Adresse du client"))
        self.items_groupbox.setTitle(_translate("BLViewerDialog", "Articles de la Livraison"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BLViewerDialog = QtWidgets.QDialog()
    ui = Ui_BLViewerDialog()
    ui.setupUi(BLViewerDialog)
    BLViewerDialog.show()
    sys.exit(app.exec())
