# Form implementation generated from reading ui file 'facturation_ci/ui/client.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClientPage(object):
    def setupUi(self, ClientPage):
        ClientPage.setObjectName("ClientPage")
        ClientPage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_button = QtWidgets.QPushButton(parent=ClientPage)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.edit_button = QtWidgets.QPushButton(parent=ClientPage)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=ClientPage)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_view = QtWidgets.QTableView(parent=ClientPage)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(ClientPage)
        QtCore.QMetaObject.connectSlotsByName(ClientPage)

    def retranslateUi(self, ClientPage):
        _translate = QtCore.QCoreApplication.translate
        ClientPage.setWindowTitle(_translate("ClientPage", "Gestion des Clients"))
        self.new_button.setText(_translate("ClientPage", "Nouveau Client"))
        self.edit_button.setText(_translate("ClientPage", "Modifier Client"))
        self.delete_button.setText(_translate("ClientPage", "Supprimer Client"))
