# Form implementation generated from reading ui file 'ui/commande.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommandePage(object):
    def setupUi(self, CommandePage):
        CommandePage.setObjectName("CommandePage")
        CommandePage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(CommandePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_button = QtWidgets.QPushButton(parent=CommandePage)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.edit_button = QtWidgets.QPushButton(parent=CommandePage)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=CommandePage)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_view = QtWidgets.QTableView(parent=CommandePage)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(CommandePage)
        QtCore.QMetaObject.connectSlotsByName(CommandePage)

    def retranslateUi(self, CommandePage):
        _translate = QtCore.QCoreApplication.translate
        CommandePage.setWindowTitle(_translate("CommandePage", "Gestion des Commandes"))
        self.new_button.setText(_translate("CommandePage", "Nouvelle Commande"))
        self.edit_button.setText(_translate("CommandePage", "Modifier Commande"))
        self.delete_button.setText(_translate("CommandePage", "Supprimer Commande"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CommandePage = QtWidgets.QWidget()
    ui = Ui_CommandePage()
    ui.setupUi(CommandePage)
    CommandePage.show()
    sys.exit(app.exec())
