# Form implementation generated from reading ui file 'ui/credit_note_list_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreditNoteListDialog(object):
    def setupUi(self, CreditNoteListDialog):
        CreditNoteListDialog.setObjectName("CreditNoteListDialog")
        CreditNoteListDialog.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreditNoteListDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.print_button = QtWidgets.QPushButton(parent=CreditNoteListDialog)
        self.print_button.setObjectName("print_button")
        self.horizontalLayout.addWidget(self.print_button)
        self.certify_button = QtWidgets.QPushButton(parent=CreditNoteListDialog)
        self.certify_button.setObjectName("certify_button")
        self.horizontalLayout.addWidget(self.certify_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.avoirs_table_view = QtWidgets.QTableView(parent=CreditNoteListDialog)
        self.avoirs_table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.avoirs_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.avoirs_table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.avoirs_table_view.setObjectName("avoirs_table_view")
        self.verticalLayout.addWidget(self.avoirs_table_view)
        self.button_box = QtWidgets.QDialogButtonBox(parent=CreditNoteListDialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(CreditNoteListDialog)
        QtCore.QMetaObject.connectSlotsByName(CreditNoteListDialog)

    def retranslateUi(self, CreditNoteListDialog):
        _translate = QtCore.QCoreApplication.translate
        CreditNoteListDialog.setWindowTitle(_translate("CreditNoteListDialog", "Listing des Factures d\'Avoir"))
        self.print_button.setText(_translate("CreditNoteListDialog", "Imprimer"))
        self.certify_button.setText(_translate("CreditNoteListDialog", "Certifier (FNE)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreditNoteListDialog = QtWidgets.QDialog()
    ui = Ui_CreditNoteListDialog()
    ui.setupUi(CreditNoteListDialog)
    CreditNoteListDialog.show()
    sys.exit(app.exec())
