# Form implementation generated from reading ui file 'facturation_ci/ui/invoice.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FacturePage(object):
    def setupUi(self, FacturePage):
        FacturePage.setObjectName("FacturePage")
        FacturePage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(FacturePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_invoice_button = QtWidgets.QPushButton(parent=FacturePage)
        self.new_invoice_button.setObjectName("new_invoice_button")
        self.horizontalLayout.addWidget(self.new_invoice_button)
        self.line = QtWidgets.QFrame(parent=FacturePage)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.certify_button = QtWidgets.QPushButton(parent=FacturePage)
        self.certify_button.setObjectName("certify_button")
        self.horizontalLayout.addWidget(self.certify_button)
        self.print_button = QtWidgets.QPushButton(parent=FacturePage)
        self.print_button.setObjectName("print_button")
        self.horizontalLayout.addWidget(self.print_button)
        self.bl_button = QtWidgets.QToolButton(parent=FacturePage)
        self.bl_button.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.bl_button.setObjectName("bl_button")
        self.horizontalLayout.addWidget(self.bl_button)
        self.create_credit_note_button = QtWidgets.QPushButton(parent=FacturePage)
        self.create_credit_note_button.setObjectName("create_credit_note_button")
        self.horizontalLayout.addWidget(self.create_credit_note_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_view = QtWidgets.QTableView(parent=FacturePage)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(FacturePage)
        QtCore.QMetaObject.connectSlotsByName(FacturePage)

    def retranslateUi(self, FacturePage):
        _translate = QtCore.QCoreApplication.translate
        FacturePage.setWindowTitle(_translate("FacturePage", "Gestion des Factures"))
        self.new_invoice_button.setText(_translate("FacturePage", "Nouvelle Facture"))
        self.certify_button.setText(_translate("FacturePage", "Certifier (FNE)"))
        self.print_button.setText(_translate("FacturePage", "Imprimer"))
        self.bl_button.setText(_translate("FacturePage", "BL"))
        self.create_credit_note_button.setText(_translate("FacturePage", "Créer un avoir"))
