# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(750, 500)
        LoginDialog.setStyleSheet("\n"
"/* --- FENÊTRE PRINCIPALE --- */\n"
"QDialog {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* --- ZONE DE GAUCHE (BRANDING) --- */\n"
"#LeftBox {\n"
"  \n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"\n"
"#BrandTitle {\n"
"    color: rgb(78, 84, 200);\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#BrandSubtitle {\n"
"    color:  rgb(78, 84, 200);\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* --- ZONE DE DROITE (FORMULAIRE) --- */\n"
"#RightBox {\n"
"    background-color: #FFFFFF;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"/* --- TITRES DROITE --- */\n"
"#LoginTitle {\n"
"    color: #333333;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"#LoginSubtitle {\n"
"    color: #999999;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* --- CHAMPS DE SAISIE --- */\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid #E0E0E0;\n"
"    padding: 10px 5px;\n"
"    background-color: transparent;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #4e54c8;\n"
"}\n"
"\n"
"/* --- BOUTON PRINCIPAL --- */\n"
"QPushButton#login_btn {\n"
"    background-color: #4e54c8;\n"
"    color: white;\n"
"    border-radius: 20px; /* Bouton pillule */\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton#login_btn:hover {\n"
"    background-color: #3f44a5;\n"
"}\n"
"QPushButton#login_btn:pressed {\n"
"    background-color: #303380;\n"
"}\n"
"\n"
"/* --- LIEN OUBLIÉ --- */\n"
"QLabel#forgot_lbl {\n"
"    color: #888888;\n"
"    font-size: 12px;\n"
"}\n"
"QLabel#forgot_lbl:hover {\n"
"    color: #4e54c8;\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"/* --- BOUTON FERMER CUSTOM --- */\n"
"QPushButton#close_btn {\n"
"    background-color: transparent;\n"
"    color: #AAAAAA;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton#close_btn:hover {\n"
"    color: #FF5555;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginDialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoginContainer = QtWidgets.QWidget(LoginDialog)
        self.LoginContainer.setStyleSheet("QWidget#LoginContainer{\n"
"    background-image: url(:/images/bg-login.png);\n"
"    border: 1px solid qlineargradient(spread:pad, x1:0.482, y1:0, x2:0.493, y2:1, stop:0 rgba(78, 84, 200, 255), stop:1 rgba(84, 90, 205, 255));\n"
"}\n"
"\n"
"")
        self.LoginContainer.setObjectName("LoginContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LoginContainer)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftBox = QtWidgets.QFrame(self.LoginContainer)
        self.LeftBox.setMinimumSize(QtCore.QSize(300, 0))
        self.LeftBox.setStyleSheet("background-color: rgba(250, 252, 246,0.3);")
        self.LeftBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftBox.setObjectName("LeftBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LeftBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.BrandTitle = QtWidgets.QLabel(self.LeftBox)
        self.BrandTitle.setStyleSheet("")
        self.BrandTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.BrandTitle.setObjectName("BrandTitle")
        self.verticalLayout_2.addWidget(self.BrandTitle)
        self.BrandSubtitle = QtWidgets.QLabel(self.LeftBox)
        self.BrandSubtitle.setStyleSheet("")
        self.BrandSubtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.BrandSubtitle.setWordWrap(True)
        self.BrandSubtitle.setObjectName("BrandSubtitle")
        self.verticalLayout_2.addWidget(self.BrandSubtitle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.LeftBox)
        self.RightBox = QtWidgets.QFrame(self.LoginContainer)
        self.RightBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightBox.setObjectName("RightBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RightBox)
        self.verticalLayout.setContentsMargins(40, 20, 40, 40)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem2)
        self.close_btn = QtWidgets.QPushButton(self.RightBox)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.headerLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.headerLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.LoginTitle = QtWidgets.QLabel(self.RightBox)
        self.LoginTitle.setObjectName("LoginTitle")
        self.verticalLayout.addWidget(self.LoginTitle)
        self.LoginSubtitle = QtWidgets.QLabel(self.RightBox)
        self.LoginSubtitle.setObjectName("LoginSubtitle")
        self.verticalLayout.addWidget(self.LoginSubtitle)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.username_input = QtWidgets.QLineEdit(self.RightBox)
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.password_input = QtWidgets.QLineEdit(self.RightBox)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.forgot_lbl = QtWidgets.QLabel(self.RightBox)
        self.forgot_lbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.forgot_lbl.setObjectName("forgot_lbl")
        self.verticalLayout.addWidget(self.forgot_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.login_btn = QtWidgets.QPushButton(self.RightBox)
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.RightBox)
        self.horizontalLayout.addWidget(self.LoginContainer)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Connexion"))
        self.BrandTitle.setText(_translate("LoginDialog", "S FACTURE +"))
        self.BrandSubtitle.setText(_translate("LoginDialog", "Gérez votre entreprise simplement"))
        self.close_btn.setText(_translate("LoginDialog", "×"))
        self.LoginTitle.setText(_translate("LoginDialog", "Bonjour !"))
        self.LoginSubtitle.setText(_translate("LoginDialog", "Entrez vos coordonnées pour continuer."))
        self.username_input.setPlaceholderText(_translate("LoginDialog", "Email ou Nom d\'utilisateur"))
        self.password_input.setPlaceholderText(_translate("LoginDialog", "Mot de passe"))
        self.forgot_lbl.setText(_translate("LoginDialog", "Mot de passe oublié ?"))
        self.login_btn.setText(_translate("LoginDialog", "SE CONNECTER"))
import img_rc
