# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(750, 500)
        LoginDialog.setStyleSheet("\n"
"/* --- FENÊTRE PRINCIPALE --- */\n"
"QDialog {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* --- ZONE DE GAUCHE (BRANDING) --- */\n"
"#LeftBox {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #4e54c8, stop:1 #8f94fb);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"#BrandTitle {\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#BrandSubtitle {\n"
"    color: #E0E0E0;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* --- ZONE DE DROITE (FORMULAIRE) --- */\n"
"#RightBox {\n"
"    background-color: #FFFFFF;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"/* --- TITRES DROITE --- */\n"
"#LoginTitle {\n"
"    color: #333333;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"#LoginSubtitle {\n"
"    color: #999999;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* --- CHAMPS DE SAISIE --- */\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid #E0E0E0;\n"
"    padding: 10px 5px;\n"
"    background-color: transparent;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #4e54c8;\n"
"}\n"
"\n"
"/* --- BOUTON PRINCIPAL --- */\n"
"QPushButton#login_btn {\n"
"    background-color: #4e54c8;\n"
"    color: white;\n"
"    border-radius: 20px; /* Bouton pillule */\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton#login_btn:hover {\n"
"    background-color: #3f44a5;\n"
"}\n"
"QPushButton#login_btn:pressed {\n"
"    background-color: #303380;\n"
"}\n"
"\n"
"/* --- LIEN OUBLIÉ --- */\n"
"QLabel#forgot_lbl {\n"
"    color: #888888;\n"
"    font-size: 12px;\n"
"}\n"
"QLabel#forgot_lbl:hover {\n"
"    color: #4e54c8;\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"/* --- BOUTON FERMER CUSTOM --- */\n"
"QPushButton#close_btn {\n"
"    background-color: transparent;\n"
"    color: #AAAAAA;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton#close_btn:hover {\n"
"    color: #FF5555;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginDialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftBox = QtWidgets.QFrame(parent=LoginDialog)
        self.LeftBox.setMinimumSize(QtCore.QSize(300, 0))
        self.LeftBox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.LeftBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.LeftBox.setObjectName("LeftBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LeftBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.BrandTitle = QtWidgets.QLabel(parent=self.LeftBox)
        self.BrandTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BrandTitle.setObjectName("BrandTitle")
        self.verticalLayout_2.addWidget(self.BrandTitle)
        self.BrandSubtitle = QtWidgets.QLabel(parent=self.LeftBox)
        self.BrandSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BrandSubtitle.setWordWrap(True)
        self.BrandSubtitle.setObjectName("BrandSubtitle")
        self.verticalLayout_2.addWidget(self.BrandSubtitle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.LeftBox)
        self.RightBox = QtWidgets.QFrame(parent=LoginDialog)
        self.RightBox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RightBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RightBox.setObjectName("RightBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RightBox)
        self.verticalLayout.setContentsMargins(40, 20, 40, 40)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem2)
        self.close_btn = QtWidgets.QPushButton(parent=self.RightBox)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.headerLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.headerLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.LoginTitle = QtWidgets.QLabel(parent=self.RightBox)
        self.LoginTitle.setObjectName("LoginTitle")
        self.verticalLayout.addWidget(self.LoginTitle)
        self.LoginSubtitle = QtWidgets.QLabel(parent=self.RightBox)
        self.LoginSubtitle.setObjectName("LoginSubtitle")
        self.verticalLayout.addWidget(self.LoginSubtitle)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.username_input = QtWidgets.QLineEdit(parent=self.RightBox)
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.password_input = QtWidgets.QLineEdit(parent=self.RightBox)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.forgot_lbl = QtWidgets.QLabel(parent=self.RightBox)
        self.forgot_lbl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.forgot_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.forgot_lbl.setObjectName("forgot_lbl")
        self.verticalLayout.addWidget(self.forgot_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.login_btn = QtWidgets.QPushButton(parent=self.RightBox)
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.RightBox)

        self.retranslateUi(LoginDialog)
        self.login_btn.clicked.connect(LoginDialog.accept) # type: ignore
        self.close_btn.clicked.connect(LoginDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Connexion"))
        self.BrandTitle.setText(_translate("LoginDialog", "FACTURATION"))
        self.BrandSubtitle.setText(_translate("LoginDialog", "Gérez votre entreprise simplement"))
        self.close_btn.setText(_translate("LoginDialog", "×"))
        self.LoginTitle.setText(_translate("LoginDialog", "Bonjour !"))
        self.LoginSubtitle.setText(_translate("LoginDialog", "Entrez vos coordonnées pour continuer."))
        self.username_input.setPlaceholderText(_translate("LoginDialog", "Email ou Nom d\'utilisateur"))
        self.password_input.setPlaceholderText(_translate("LoginDialog", "Mot de passe"))
        self.forgot_lbl.setText(_translate("LoginDialog", "Mot de passe oublié ?"))
        self.login_btn.setText(_translate("LoginDialog", "SE CONNECTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
