# Form implementation generated from reading ui file 'facturation_ci/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f5f5f7;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    border: none;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 15px;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-left: 4px solid #2980b9;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #34495e;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #ecf0f1;\n"
"    color: #2c3e50;\n"
"    padding: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nav_menu = QtWidgets.QListWidget(parent=self.centralwidget)
        self.nav_menu.setMinimumSize(QtCore.QSize(180, 0))
        self.nav_menu.setMaximumSize(QtCore.QSize(180, 16777215))
        self.nav_menu.setStyleSheet("")
        self.nav_menu.setObjectName("nav_menu")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.nav_menu.addItem(item)
        self.horizontalLayout.addWidget(self.nav_menu)
        self.stacked_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stacked_widget.setStyleSheet("QStackedWidget {\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #ddd;\n"
"}")
        self.stacked_widget.setObjectName("stacked_widget")
        self.dashboard_page = QtWidgets.QWidget()
        self.dashboard_page.setObjectName("dashboard_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dashboard_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.dashboard_page)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.stacked_widget.addWidget(self.dashboard_page)
        self.commandes_page = QtWidgets.QWidget()
        self.commandes_page.setObjectName("commandes_page")
        self.verticalLayout_commandes = QtWidgets.QVBoxLayout(self.commandes_page)
        self.verticalLayout_commandes.setObjectName("verticalLayout_commandes")
        self.label_commandes = QtWidgets.QLabel(parent=self.commandes_page)
        self.label_commandes.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_commandes.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_commandes.setObjectName("label_commandes")
        self.verticalLayout_commandes.addWidget(self.label_commandes)
        self.stacked_widget.addWidget(self.commandes_page)
        self.invoices_page = QtWidgets.QWidget()
        self.invoices_page.setObjectName("invoices_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.invoices_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.invoices_page)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.stacked_widget.addWidget(self.invoices_page)
        self.avoirs_page = QtWidgets.QWidget()
        self.avoirs_page.setObjectName("avoirs_page")
        self.verticalLayout_avoirs = QtWidgets.QVBoxLayout(self.avoirs_page)
        self.verticalLayout_avoirs.setObjectName("verticalLayout_avoirs")
        self.label_avoirs = QtWidgets.QLabel(parent=self.avoirs_page)
        self.label_avoirs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_avoirs.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_avoirs.setObjectName("label_avoirs")
        self.verticalLayout_avoirs.addWidget(self.label_avoirs)
        self.stacked_widget.addWidget(self.avoirs_page)
        self.clients_page = QtWidgets.QWidget()
        self.clients_page.setObjectName("clients_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.clients_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.clients_page)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.stacked_widget.addWidget(self.clients_page)
        self.products_page = QtWidgets.QWidget()
        self.products_page.setObjectName("products_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.products_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.products_page)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.stacked_widget.addWidget(self.products_page)
        self.reports_page = QtWidgets.QWidget()
        self.reports_page.setObjectName("reports_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.reports_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.reports_page)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.stacked_widget.addWidget(self.reports_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.settings_page)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.stacked_widget.addWidget(self.settings_page)
        self.horizontalLayout.addWidget(self.stacked_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Logiciel de Facturation"))
        __sortingEnabled = self.nav_menu.isSortingEnabled()
        self.nav_menu.setSortingEnabled(False)
        item = self.nav_menu.item(0)
        item.setText(_translate("MainWindow", "Dashboard"))
        item = self.nav_menu.item(1)
        item.setText(_translate("MainWindow", "Commandes"))
        item = self.nav_menu.item(2)
        item.setText(_translate("MainWindow", "Factures"))
        item = self.nav_menu.item(3)
        item.setText(_translate("MainWindow", "Avoirs"))
        item = self.nav_menu.item(4)
        item.setText(_translate("MainWindow", "Clients"))
        item = self.nav_menu.item(5)
        item.setText(_translate("MainWindow", "Produits"))
        item = self.nav_menu.item(6)
        item.setText(_translate("MainWindow", "Rapports"))
        item = self.nav_menu.item(7)
        item.setText(_translate("MainWindow", "Paramètres"))
        self.nav_menu.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Contenu du Dashboard"))
        self.label_commandes.setText(_translate("MainWindow", "Contenu des Commandes"))
        self.label_2.setText(_translate("MainWindow", "Contenu des Factures"))
        self.label_avoirs.setText(_translate("MainWindow", "Contenu des Avoirs"))
        self.label_3.setText(_translate("MainWindow", "Contenu des Clients"))
        self.label_4.setText(_translate("MainWindow", "Contenu des Produits"))
        self.label_5.setText(_translate("MainWindow", "Contenu des Rapports"))
        self.label_6.setText(_translate("MainWindow", "Contenu des Paramètres"))
