# Form implementation generated from reading ui file 'ui/new_invoice_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewInvoiceDialog(object):
    def setupUi(self, NewInvoiceDialog):
        NewInvoiceDialog.setObjectName("NewInvoiceDialog")
        NewInvoiceDialog.resize(700, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewInvoiceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_groupbox = QtWidgets.QGroupBox(parent=NewInvoiceDialog)
        self.filter_groupbox.setObjectName("filter_groupbox")
        self.formLayout = QtWidgets.QFormLayout(self.filter_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.client_label = QtWidgets.QLabel(parent=self.filter_groupbox)
        self.client_label.setObjectName("client_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.client_label)
        self.client_filter_combo = QtWidgets.QComboBox(parent=self.filter_groupbox)
        self.client_filter_combo.setObjectName("client_filter_combo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.client_filter_combo)
        self.date_label = QtWidgets.QLabel(parent=self.filter_groupbox)
        self.date_label.setObjectName("date_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.date_label)
        self.date_filter_combo = QtWidgets.QComboBox(parent=self.filter_groupbox)
        self.date_filter_combo.setObjectName("date_filter_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.date_filter_combo)
        self.commande_code_label = QtWidgets.QLabel(parent=self.filter_groupbox)
        self.commande_code_label.setObjectName("commande_code_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.commande_code_label)
        self.commande_code_filter_combo = QtWidgets.QComboBox(parent=self.filter_groupbox)
        self.commande_code_filter_combo.setObjectName("commande_code_filter_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.commande_code_filter_combo)
        self.verticalLayout.addWidget(self.filter_groupbox)
        self.commandes_table_view = QtWidgets.QTableView(parent=NewInvoiceDialog)
        self.commandes_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.commandes_table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.commandes_table_view.setObjectName("commandes_table_view")
        self.verticalLayout.addWidget(self.commandes_table_view)
        self.button_box = QtWidgets.QDialogButtonBox(parent=NewInvoiceDialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(NewInvoiceDialog)
        QtCore.QMetaObject.connectSlotsByName(NewInvoiceDialog)

    def retranslateUi(self, NewInvoiceDialog):
        _translate = QtCore.QCoreApplication.translate
        NewInvoiceDialog.setWindowTitle(_translate("NewInvoiceDialog", "Nouvelle Facture à partir d\'une Commande"))
        self.filter_groupbox.setTitle(_translate("NewInvoiceDialog", "Rechercher une Commande"))
        self.client_label.setText(_translate("NewInvoiceDialog", "Client :"))
        self.date_label.setText(_translate("NewInvoiceDialog", "Date :"))
        self.commande_code_label.setText(_translate("NewInvoiceDialog", "Code Commande :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewInvoiceDialog = QtWidgets.QDialog()
    ui = Ui_NewInvoiceDialog()
    ui.setupUi(NewInvoiceDialog)
    NewInvoiceDialog.show()
    sys.exit(app.exec())
