# Form implementation generated from reading ui file 'facturation_ci/ui/permissions.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PermissionsPage(object):
    def setupUi(self, PermissionsPage):
        PermissionsPage.setObjectName("PermissionsPage")
        PermissionsPage.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PermissionsPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.label_roles = QtWidgets.QLabel(parent=PermissionsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_roles.setFont(font)
        self.label_roles.setObjectName("label_roles")
        self.leftLayout.addWidget(self.label_roles)
        self.roles_list = QtWidgets.QListWidget(parent=PermissionsPage)
        self.roles_list.setObjectName("roles_list")
        self.leftLayout.addWidget(self.roles_list)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.label_perms = QtWidgets.QLabel(parent=PermissionsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_perms.setFont(font)
        self.label_perms.setObjectName("label_perms")
        self.rightLayout.addWidget(self.label_perms)
        self.permissions_list = QtWidgets.QListWidget(parent=PermissionsPage)
        self.permissions_list.setObjectName("permissions_list")
        self.rightLayout.addWidget(self.permissions_list)
        self.save_button = QtWidgets.QPushButton(parent=PermissionsPage)
        self.save_button.setObjectName("save_button")
        self.rightLayout.addWidget(self.save_button)
        self.horizontalLayout.addLayout(self.rightLayout)

        self.retranslateUi(PermissionsPage)
        QtCore.QMetaObject.connectSlotsByName(PermissionsPage)

    def retranslateUi(self, PermissionsPage):
        _translate = QtCore.QCoreApplication.translate
        PermissionsPage.setWindowTitle(_translate("PermissionsPage", "Gestion des Permissions"))
        self.label_roles.setText(_translate("PermissionsPage", "Rôles"))
        self.label_perms.setText(_translate("PermissionsPage", "Permissions"))
        self.save_button.setText(_translate("PermissionsPage", "Enregistrer les modifications"))
