# Form implementation generated from reading ui file 'facturation_ci/ui/product.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductPage(object):
    def setupUi(self, ProductPage):
        ProductPage.setObjectName("ProductPage")
        ProductPage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_button = QtWidgets.QPushButton(parent=ProductPage)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.edit_button = QtWidgets.QPushButton(parent=ProductPage)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=ProductPage)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_view = QtWidgets.QTableView(parent=ProductPage)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(ProductPage)
        QtCore.QMetaObject.connectSlotsByName(ProductPage)

    def retranslateUi(self, ProductPage):
        _translate = QtCore.QCoreApplication.translate
        ProductPage.setWindowTitle(_translate("ProductPage", "Gestion des Produits"))
        self.new_button.setText(_translate("ProductPage", "Nouveau Produit"))
        self.edit_button.setText(_translate("ProductPage", "Modifier Produit"))
        self.delete_button.setText(_translate("ProductPage", "Supprimer Produit"))
