# Form implementation generated from reading ui file 'facturation_ci/ui/settings_card.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsCard(object):
    def setupUi(self, SettingsCard):
        SettingsCard.setObjectName("SettingsCard")
        SettingsCard.resize(250, 120)
        SettingsCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        SettingsCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsCard)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=SettingsCard)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.desc_label = QtWidgets.QLabel(parent=SettingsCard)
        self.desc_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.verticalLayout.addWidget(self.desc_label)

        self.retranslateUi(SettingsCard)
        QtCore.QMetaObject.connectSlotsByName(SettingsCard)

    def retranslateUi(self, SettingsCard):
        _translate = QtCore.QCoreApplication.translate
        SettingsCard.setWindowTitle(_translate("SettingsCard", "SettingsCard"))
        self.title_label.setText(_translate("SettingsCard", "Title"))
        self.desc_label.setText(_translate("SettingsCard", "Description goes here..."))
