# Form implementation generated from reading ui file 'facturation_ci/ui/settings.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsPage(object):
    def setupUi(self, SettingsPage):
        SettingsPage.setObjectName("SettingsPage")
        SettingsPage.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.company_groupbox = QtWidgets.QGroupBox(parent=SettingsPage)
        self.company_groupbox.setObjectName("company_groupbox")
        self.formLayout = QtWidgets.QFormLayout(self.company_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_name)
        self.name_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_edit)
        self.label_address = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_address.setObjectName("label_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_address)
        self.address_edit = QtWidgets.QTextEdit(parent=self.company_groupbox)
        self.address_edit.setObjectName("address_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.address_edit)
        self.label_phone = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_phone.setObjectName("label_phone")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_phone)
        self.phone_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.phone_edit.setObjectName("phone_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phone_edit)
        self.label_email = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_email)
        self.email_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.email_edit.setObjectName("email_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.email_edit)
        self.label_tax_id = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_tax_id.setObjectName("label_tax_id")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_tax_id)
        self.tax_id_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.tax_id_edit.setObjectName("tax_id_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tax_id_edit)
        self.label_pos = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_pos.setObjectName("label_pos")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_pos)
        self.pos_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.pos_edit.setObjectName("pos_edit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pos_edit)
        self.label_fne_api_key = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_fne_api_key.setObjectName("label_fne_api_key")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_fne_api_key)
        self.fne_api_key_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.fne_api_key_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.fne_api_key_edit.setObjectName("fne_api_key_edit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fne_api_key_edit)
        
        # --- DÉBUT DES AJOUTS ---
        self.label_tax_regime = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_tax_regime.setObjectName("label_tax_regime")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_tax_regime)
        self.tax_regime_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.tax_regime_edit.setObjectName("tax_regime_edit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tax_regime_edit)
        
        self.label_tax_office = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_tax_office.setObjectName("label_tax_office")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_tax_office)
        self.tax_office_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.tax_office_edit.setObjectName("tax_office_edit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tax_office_edit)
        
        self.label_rccm = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_rccm.setObjectName("label_rccm")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_rccm)
        self.rccm_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.rccm_edit.setObjectName("rccm_edit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rccm_edit)
        
        self.label_bank_details = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_bank_details.setObjectName("label_bank_details")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_bank_details)
        self.bank_details_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.bank_details_edit.setObjectName("bank_details_edit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.bank_details_edit)
        
        self.label_establishment = QtWidgets.QLabel(parent=self.company_groupbox)
        self.label_establishment.setObjectName("label_establishment")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_establishment)
        self.establishment_edit = QtWidgets.QLineEdit(parent=self.company_groupbox)
        self.establishment_edit.setObjectName("establishment_edit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.establishment_edit)
        # --- FIN DES AJOUTS ---
        
        self.verticalLayout.addWidget(self.company_groupbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save_button = QtWidgets.QPushButton(parent=SettingsPage)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SettingsPage)
        QtCore.QMetaObject.connectSlotsByName(SettingsPage)

    def retranslateUi(self, SettingsPage):
        _translate = QtCore.QCoreApplication.translate
        SettingsPage.setWindowTitle(_translate("SettingsPage", "Paramètres"))
        self.company_groupbox.setTitle(_translate("SettingsPage", "Informations de l'Entreprise"))
        self.label_name.setText(_translate("SettingsPage", "Nom de l'entreprise :"))
        self.label_address.setText(_translate("SettingsPage", "Adresse :"))
        self.label_phone.setText(_translate("SettingsPage", "Téléphone :"))
        self.label_email.setText(_translate("SettingsPage", "Email :"))
        self.label_tax_id.setText(_translate("SettingsPage", "N° de Contribuable :"))
        self.label_pos.setText(_translate("SettingsPage", "Point de Vente :"))
        self.label_fne_api_key.setText(_translate("SettingsPage", "Clé d'API FNE :"))
        
        # --- DÉBUT DES AJOUTS ---
        self.label_tax_regime.setText(_translate("SettingsPage", "Régime d'imposition :"))
        self.label_tax_office.setText(_translate("SettingsPage", "Centre des impôts :"))
        self.label_rccm.setText(_translate("SettingsPage", "N° RCCM :"))
        self.label_bank_details.setText(_translate("SettingsPage", "Références bancaires :"))
        self.label_establishment.setText(_translate("SettingsPage", "Établissement :"))
        # --- FIN DES AJOUTS ---
        
        self.save_button.setText(_translate("SettingsPage", "Enregistrer les modifications"))