# Form implementation generated from reading ui file 'facturation_ci/ui/user_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserDialog(object):
    def setupUi(self, UserDialog):
        UserDialog.setObjectName("UserDialog")
        UserDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=UserDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.username_edit = QtWidgets.QLineEdit(parent=UserDialog)
        self.username_edit.setObjectName("username_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.username_edit)
        self.label_2 = QtWidgets.QLabel(parent=UserDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.fullname_edit = QtWidgets.QLineEdit(parent=UserDialog)
        self.fullname_edit.setObjectName("fullname_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fullname_edit)
        self.label_3 = QtWidgets.QLabel(parent=UserDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.password_edit = QtWidgets.QLineEdit(parent=UserDialog)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setObjectName("password_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_edit)
        self.label_4 = QtWidgets.QLabel(parent=UserDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.role_combo = QtWidgets.QComboBox(parent=UserDialog)
        self.role_combo.setObjectName("role_combo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.role_combo)
        self.label_5 = QtWidgets.QLabel(parent=UserDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.active_check = QtWidgets.QCheckBox(parent=UserDialog)
        self.active_check.setChecked(True)
        self.active_check.setObjectName("active_check")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.active_check)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=UserDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(UserDialog)
        self.buttonBox.accepted.connect(UserDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(UserDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserDialog)

    def retranslateUi(self, UserDialog):
        _translate = QtCore.QCoreApplication.translate
        UserDialog.setWindowTitle(_translate("UserDialog", "Utilisateur"))
        self.label.setText(_translate("UserDialog", "Nom d\'utilisateur :"))
        self.label_2.setText(_translate("UserDialog", "Nom complet :"))
        self.label_3.setText(_translate("UserDialog", "Mot de passe :"))
        self.label_4.setText(_translate("UserDialog", "Rôle :"))
        self.label_5.setText(_translate("UserDialog", "Actif :"))
